#
#
#

version: '2'

services:
  tb:
    image: "thingsboard/application:1.4.0"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683:5683/udp"
    env_file:
      - tb.env
    environment:
      - ADD_SCHEMA_AND_SYSTEM_DATA=${ADD_SCHEMA_AND_SYSTEM_DATA}
      - ADD_DEMO_DATA=${ADD_DEMO_DATA}
    volumes:
      - "${HSQLDB_DATA_DIR}:/usr/share/thingsboard/data/sql"
    entrypoint: /run-application.sh
  cassandra:
    image: "cassandra:3.11.2"
    ports:
      - "9042"
      - "9160"
    volumes:
      - "${CASSANDRA_DATA_DIR}:/var/lib/cassandra"
  zk:
    image: "zookeeper:3.4.10"
    ports:
      - "2181"
    restart: always
  postgres:
    image: "postgres:9.6"
    ports:
    - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
